"use client"

import React, { useState, useEffect } from 'react'
import { RotateCcw, Clock, Infinity } from 'lucide-react'

const CorePrinciples = () => {
    const [scrollY, setScrollY] = useState(0)

    useEffect(() => {
        const handleScroll = () => {
            setScrollY(window.scrollY)
        }

        window.addEventListener('scroll', handleScroll)
        return () => window.removeEventListener('scroll', handleScroll)
    }, [])

    return (
        <section className="py-24 relative overflow-hidden min-h-screen">
            {/* Parallax Background */}
            <div 
                className="absolute bg-cover bg-center"
                style={{
                    backgroundImage: "url('/assets/images/360_F_471333224_bQbXMG1TuzIed78bfWp2UVLN1kyhoQYf.jpg')",
                    transform: `translateY(${scrollY * 0.1}px)`,
                    backgroundAttachment: 'fixed',
                    backgroundSize: 'cover',
                    height: '150%',
                    width: '100%',
                    top: '-25%',
                    left: '0',
                    willChange: 'transform'
                }}
            />
            {/* Dark overlay for better text readability */}
            <div className="absolute inset-0 bg-slate-900/30"></div>
            
            {/* Content overlay */}
            <div className="relative z-10">
                <div className="container mx-auto px-6">
                <h2 className="text-4xl font-bold text-white mb-16 text-center">Core Principles</h2>

                {/* Asymmetric Mosaic: 1 hero (left) + 2 stacked (right) */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
                    {/* HERO: Inversion (spans 2 rows on desktop) */}
                    <article className="lg:col-span-2 lg:row-span-2 rounded-2xl p-10 bg-gradient-to-br from-slate-800 to-slate-900 border border-white/10 shadow-xl"> 
                        <div className="flex items-center gap-4 mb-6">
                            <div className="w-14 h-14 rounded-xl bg-blue-500/15 flex items-center justify-center">
                                <RotateCcw className="w-8 h-8 text-blue-400" />
                            </div>
                            <h3 className="text-3xl font-semibold text-white">Inversion</h3>
                        </div>
                        <p className="text-slate-300 text-lg leading-relaxed max-w-3xl">
                            Foundational harmonic principle: forms emerge from mirrored opposites.
                            Stability is generated by tension-balanced symmetry—the first cause in your Codex.
                        </p>

                        {/* Optional bullets for depth */}
                        <ul className="mt-8 grid sm:grid-cols-2 gap-4 text-slate-300">
                            <li className="rounded-lg bg-white/5 border border-white/10 p-4">
                                Phase-flip symmetry → structural coherence
                            </li>
                            <li className="rounded-lg bg-white/5 border border-white/10 p-4">
                                Primary inversion as max-pressure constant (Iₚ)
                            </li>
                            <li className="rounded-lg bg-white/5 border border-white/10 p-4">
                                Predicts zone formation across scales
                            </li>
                            <li className="rounded-lg bg-white/5 border border-white/10 p-4">
                                Basis for Codex security primitives
                            </li>
                        </ul>
                    </article>

                    {/* MINOR: Time */}
                    <article className="rounded-2xl p-8 bg-slate-800/60 border border-white/10">
                        <div className="flex items-center gap-3 mb-4">
                            <div className="w-12 h-12 rounded-xl bg-purple-500/15 flex items-center justify-center">
                                <Clock className="w-7 h-7 text-purple-300" />
                            </div>
                            <h3 className="text-2xl font-semibold text-white">Time</h3>
                        </div>
                        <p className="text-slate-300 leading-relaxed">
                            Not a dimension—it&apos;s a refresh rate. Experience tracks the universe&apos;s
                            update cycles (TIUs) and harmonic lock-in.
                        </p>
                    </article>

                    {/* MINOR: Totality (12) */}
                    <article className="rounded-2xl p-8 bg-slate-800/60 border border-white/10">
                        <div className="flex items-center gap-3 mb-4">
                            <div className="w-12 h-12 rounded-xl bg-emerald-500/15 flex items-center justify-center">
                                <Infinity className="w-7 h-7 text-emerald-300" />
                            </div>
                            <h3 className="text-2xl font-semibold text-white">Totality (12)</h3>
                        </div>
                        <p className="text-slate-300 leading-relaxed">
                            The 12-zone cycle—the full harmonic lattice that organizes structure,
                            motion, and allowable states.
                        </p>
                    </article>
                </div>
                </div>
            </div>
        </section>
    )
}

export default CorePrinciples
